;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("org-capture-last-stored"
  (filename . "~/org/inbox.org")
  (front-context-string . "** TODO Devo ver")
  (rear-context-string)
  (position . 9)
  (last-modified 27305 3076 623643 73000))
)
